on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://github.com/Eunice2000/owaspwithfrontend'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      # Add a step to send a message to Slack
      - name: Send Message to Slack
        run: |
          SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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

          # Use a wildcard to dynamically locate the ZAP scan report
          ZAP_REPORT_PATH=$(find /github/workspace -name "*.html" -print -quit)

          if [ -n "$ZAP_REPORT_PATH" ]; then
            curl -X POST -H "Content-type: multipart/form-data" -F "file=@$ZAP_REPORT_PATH" -F "channels=#my-channel-here" $SLACK_WEBHOOK_URL
          else
            echo "ZAP scan report file not found."
          fi
        env:
          SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
