name: Dependency Check for React and Next.js

on:
  push:
    branches:
      - main

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Run OWASP Dependency-Check
        run: |
          npm install -g dependency-check
          dependency-check .
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

