on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://github.com/Eunice2000/owaspwithfrontend'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      # Move the ZAP scan report to a known location
      - name: Move ZAP Report
        run: mv /github/workspace/report.html /github/workspace/zap_report/report.html

      # Send the ZAP scan report to Slack
      - name: Send ZAP Scan Report to Slack
        run: |
          SLACK_WEBHOOK_URL=https://hooks.slack.com/services/your/webhook/url
          ZAP_REPORT_PATH=/github/workspace/zap_report/report.html

          curl -X POST -H "Content-type: multipart/form-data" -F "file=@$ZAP_REPORT_PATH" -F "channels=#your-slack-channel" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
